variables:
  ARM_PASS: $(adminpass)

trigger:
- none

pool: #linux
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-basic-linux'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMME'
    subscriptionId: '1c97e8fc-0515-494b-94f2-01d15b41c22d' #Change for yours
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm-quickstart-templates-another'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-webAppName dejann-another'
    #-administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'

